### ISSUE TITLE
Install instructions don't work

### ISSUE THREAD

**Issue by LinearParadox** [raphael-group/GASTON#4]
Not sure why this is, and I suspect it's some weird conda behavior with editable packages:

pip install -e (gaston_path) does not install to the site packages folder. You can still run gaston from the command line, but in notebooks you get errors like so:

```
     12 import sys
     13 from importlib import reload
---> 15 from gaston import neural_net,cluster_plotting, dp_related, segmented_fit, restrict_spots, model_selection
     16 from gaston import binning_and_plotting, isodepth_scaling, run_slurm_scripts, parse_adata
     17 from gaston import spatial_gene_classification, plot_cell_types, filter_genes, process_NN_output

ImportError: cannot import name 'neural_net' from 'gaston' (unknown location)
```

This is fixed by doing: 
```
pip install git+https://github.com/raphael-group/gaston@main
```

**Comment by uthsavc** [comment]
Thanks for figuring this out, and sorry for the problems with the conda installation! We will soon put our package on PyPi/Bioconda, rather than having to install the package manually, which should hopefully fix these issues.

Leaving this issue open until we make the package installable from pip/bioconda.

**Comment by uthsavc** [comment]
We just added GASTON to PyPI: https://pypi.org/project/gaston-spatial/

We will add to Bioconda in the future.
